name: CI

on: [push]

jobs:
  build:
    runs-on: osgeo/gdal:ubuntu-full-3.0.2 
    steps:
    - name: 'Checkout the source code from GitHub'
      uses: actions/checkout@master
      with:
        submodules: true
    - name: 'Install ndjson-cli'
      run: |
        apt-get update
        apt-get -y install curl gnupg
        curl -sL https://deb.nodesource.com/setup_11.x  | bash -
        apt-get -y install nodejs
        npm i -g ndjson-cli@0.3.1
        node -v
        npm -v
        ndjson-cat -V
    - name: 'Build map-data'
      run: ./tools/entrypoint.sh