name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout the source code from GitHub'
      uses: actions/checkout@master
      with:
        submodules: true

    - name: 'Build docker image'
      run: docker build . --tag maps:$(date +%s)
