name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout the source code from GitHub'
      uses: actions/checkout@master
      with:
        submodules: true

    - name: 'Build map-data'
      uses: ./.github/actions/build-map-data

    - name: 'Debug output'
      run: |
        apt-get install tree 
        tree .
  